#!/usr/bin/env python

import argparse
import mc_bin_client
import re

NUM_VBUCKETS = 1024

class StatStruct():
    def __init__(self, state, host, port):
        self.state = state
        self.host = host
        self.port = port
        self.stats = {}

    def add_stat(self, key, value):
        self.stats[key] = value

    def get_stat(self, key):
        return self.stats[key]

def parse_hosts(host_arg):
    servers = []

    host_list = host_arg[0].split(',')
    for i in range(len(host_list)):
        server = tuple(host_list[i].split(':'))
        servers.append(server)
        
    return servers

def get_stats_from_host(host, port, arg):
    print host, port, arg
    mc = mc_bin_client.MemcachedClient(host, port)
    stats = mc.stats(arg)
    mc.close()
    return stats

def do_vbucket_num_items_diff(hosts, key):
    all = {}
    for i in range(NUM_VBUCKETS):
        all[i] = []

    for host in hosts:
        ip = host[0]
        port = int(host[1])

        stats = get_stats_from_host(ip, port, 'vbucket-details')

        for i in range(NUM_VBUCKETS):
            name = "vb_%d" % (i)
            data = StatStruct(stats[name], ip, port)


            name = "vb_%d:%s" % (i, key)
            data.add_stat(key, stats[name])
        
            all[i].append(data)

    return all

def compare_by_vbucket(all, stat):
    for vb in range(NUM_VBUCKETS):
        vb_stats = all[vb]

        lastNode = None
        for node in vb_stats:
            if lastNode is not None:
                a = lastNode.get_stat(stat)
                b = node.get_stat(stat)
                if a != b:
                    print_node_stats_for_vbucket(all, vb, stat)
                    break
            lastNode = node
        lastNode = None

def print_node_stats_for_vbucket(all, vb, stat):
    vb_stats = all[vb]
    for node in vb_stats:
        print vb, node.state, node.get_stat(stat), node.port

def main():
    parser = argparse.ArgumentParser(prog='vbcheck',
                                     usage='%(prog)s [options]',
                                     add_help=False)

    parser.add_argument('-h', '--hosts', default=['127.0.0.1:9000'], nargs='+',
                        help='the ip:port address of the server(s) to test')
    parser.add_argument('-s', '--stat', default='num_items',
                        help='backend server to run against')

    args = parser.parse_args()
    hosts = parse_hosts(args.hosts)

    stat = args.stat
    all = do_vbucket_num_items_diff(hosts, stat)
    compare_by_vbucket(all, stat)


if __name__ == '__main__':
    main()
